const rooms = [
  {
    number: 'soba2',
    mainImg: 'assets/img/soba2/2_2.jpg',
    smallImg: [
      'assets/img/soba2/2_1.jpg',
      'assets/img/soba2/2_2.jpg',
      'assets/img/soba2/2_3.jpg',
      'assets/img/soba2/2_4.jpg',
      'assets/img/soba2/2_5.jpg',
      'assets/img/soba2/2_6.jpg',
      'assets/img/soba2/2_7.jpg',
    ],
  },
  {
    number: 'soba3',
    mainImg: 'assets/img/soba3/3_2.jpg',
    smallImg: [
      'assets/img/soba3/3_1.jpg',
      'assets/img/soba3/3_2.jpg',
      'assets/img/soba3/3_3.jpg',
      'assets/img/soba3/3_4.jpg',
      'assets/img/soba3/3_5.jpg',
      'assets/img/soba3/3_6.jpg',
      'assets/img/soba3/3_7.jpg',
      'assets/img/soba3/3_8.jpg',
    ],
  },
  {
    number: 'soba5',
    mainImg: 'assets/img/soba5/5_1.jpg',
    smallImg: [
      'assets/img/soba5/5_1.jpg',
      'assets/img/soba5/5_2.jpg',
      'assets/img/soba5/5_3.jpg',
      'assets/img/soba5/5_4.jpg',
      'assets/img/soba5/5_5.jpg',
      'assets/img/soba5/5_6.jpg',
      'assets/img/soba5/5_7.jpg',
    ],
  },
  {
    number: 'soba6',
    mainImg: 'assets/img/soba6/6_1.jpg',
    smallImg: [
      'assets/img/soba6/6_1.jpg',
      'assets/img/soba6/6_2.jpg',
      'assets/img/soba6/6_3.jpg',
      'assets/img/soba6/6_4.jpg',
      'assets/img/soba6/6_5.jpg',
      'assets/img/soba6/6_6.jpg',
      'assets/img/soba6/6_7.jpg',
      'assets/img/soba6/6_8.jpg',
      'assets/img/soba6/6_9.jpg',
      'assets/img/soba6/6_10.jpg',
      'assets/img/soba6/6_11.jpg',
    ],
  },
  {
    number: 'soba7',
    mainImg: 'assets/img/soba7/7_3.jpg',
    smallImg: [
      'assets/img/soba7/7_1.jpg',
      'assets/img/soba7/7_2.jpg',
      'assets/img/soba7/7_3.jpg',
      'assets/img/soba7/7_4.jpg',
      'assets/img/soba7/7_5.jpg',
      'assets/img/soba7/7_6.jpg',
      'assets/img/soba7/7_7.jpg',
      'assets/img/soba7/7_8.jpg',
      'assets/img/soba7/7_9.jpg',
      'assets/img/soba7/7_10.jpg',
    ],
  },
  {
    number: 'soba24',
    mainImg: 'assets/img/soba24/24_4.jpg',
    smallImg: [
      'assets/img/soba24/24_1.jpg',
      'assets/img/soba24/24_2.jpg',
      'assets/img/soba24/24_3.jpg',
      'assets/img/soba24/24_4.jpg',
      'assets/img/soba24/24_5.jpg',
      'assets/img/soba24/24_6.jpg',
      'assets/img/soba24/24_7.jpg',
      'assets/img/soba24/24_8.jpg',
      'assets/img/soba24/24_9.jpg',
    ],
  },
];
export default rooms;
